### PR TITLE
Null value test.

### PR DESCRIPTION
**Pull request by WORMSS**
Since typeof null == 'object', I also added tests to make sure data is not null.

### CODE REVIEW

**Comment by mohsen1** [comment]
👍

**Comment by WORMSS** [comment]
Thank you. I was originally hoping to fix #1.
Unfortunately it seems it is `table-cli` that is the problem. It is unable to accept null as a value.

But without altering the data or doing a deep clone and replacing `null` values with `'null'` before it gets sent to `table-cli` I wouldn't be able to fix.

Could maybe analyse the data and test if anything would cause an error and quit out, but again, that wouldn't fix #1, it would only stop better-console from throwing the error by proxy.

**Comment by mohsen1** [comment]
I would suggest bumping version of cli-table to `cli-table@0.3.1`. please try that and see if that fixes it

**Comment by WORMSS** [comment]
I'm afraid not. They have already fixed the issue, and it is on the master branch of Automattic/cli-table@ea213ed3bce90c6b94694999bf809da1b08ce645 but I guess for what ever reason, they have yet to make this public.

Again, this STILL technically does not fix #1 as @estock requested to have the word `'null'` there, but their fix fills the table with blank.

**Pull request merged**
